# Generated by Django 3.2.6 on 2021-08-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_auto_20210828_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
