# Generated by Django 3.2.6 on 2021-08-28 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_question_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='status',
            new_name='active',
        ),
        migrations.RemoveField(
            model_name='question',
            name='updated',
        ),
    ]
