# Generated by Django 3.2.6 on 2021-08-28 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_auto_20210828_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='created',
        ),
    ]
