# Generated by Django 3.2.6 on 2021-08-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0009_auto_20210829_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='duration',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
