# Generated by Django 3.2.6 on 2021-08-29 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0011_alter_question_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
